# Generated by Django 4.1.7 on 2023-03-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("birthday", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destination1",
            name="img",
            field=models.ImageField(upload_to="pics1"),
        ),
    ]
